In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('heart.csv').drop_duplicates()
df.drop([85], inplace=True)
df.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

In [6]:
df = df.sample(frac=1).reset_index(drop=True)
df.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   48    1   0     124   274    0        0       166     0      0.5    1   
1   42    1   0     140   226    0        1       178     0      0.0    2   
2   38    1   2     138   175    0        1       173     0      0.0    2   
3   56    1   3     120   193    0        0       162     0      1.9    1   
4   65    1   0     135   254    0        0       127     0      2.8    1   

   caa  thall  output  
0    0      3       0  
1    0      2       1  
2    4      2       1  
3    0      3       1  
4    1      3       0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       301 non-null    int64  
 1   sex       301 non-null    int64  
 2   cp        301 non-null    int64  
 3   trtbps    301 non-null    int64  
 4   chol      301 non-null    int64  
 5   fbs       301 non-null    int64  
 6   restecg   301 non-null    int64  
 7   thalachh  301 non-null    int64  
 8   exng      301 non-null    int64  
 9   oldpeak   301 non-null    float64
 10  slp       301 non-null    int64  
 11  caa       301 non-null    int64  
 12  thall     301 non-null    int64  
 13  output    301 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.0 KB


In [37]:
int_cols = list(range(14))
int_cols.remove(9)
for i in int_cols:
    df.iloc[:, i] = df.iloc[:, i].astype('int32')
df.oldpeak = df.oldpeak.astype('float32')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       301 non-null    int32  
 1   sex       301 non-null    int32  
 2   cp        301 non-null    int32  
 3   trtbps    301 non-null    int32  
 4   chol      301 non-null    int32  
 5   fbs       301 non-null    int32  
 6   restecg   301 non-null    int32  
 7   thalachh  301 non-null    int32  
 8   exng      301 non-null    int32  
 9   oldpeak   301 non-null    float32
 10  slp       301 non-null    int32  
 11  caa       301 non-null    int32  
 12  thall     301 non-null    int32  
 13  output    301 non-null    int32  
dtypes: float32(1), int32(13)
memory usage: 16.6 KB


In [51]:
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split
X = scale(np.array(df.drop('output', axis = 1), dtype = 'float'), with_std = True, with_mean = True)
y = np.array(df.output)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

In [52]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=123, n_jobs=-1)
rfc.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=123)

In [57]:
y_rfc = rfc.predict(X_test)
y_rfc

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0])

In [55]:
y_test

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0])

In [72]:
from sklearn import metrics

In [78]:
print('accuracy =', round(metrics.accuracy_score(y_test, y_rfc), 5))
print('precision =', round(metrics.precision_score(y_test, y_rfc), 5))
print('recall =', round(metrics.recall_score(y_test, y_rfc), 2))
print('f1 =', round(metrics.f1_score(y_test, y_rfc), 2))

accuracy = 0.79121
precision = 0.74
recall = 0.86
f1 = 0.8


In [66]:
from sklearn import linear_model
rc = linear_model.RidgeClassifier(random_state=123)
rc.fit(X_train, y_train)

RidgeClassifier(random_state=123)

In [75]:
y_rc = rc.predict(X_test)
y_rc

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0])

In [76]:
y_test

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0])

In [79]:
print('accuracy =', round(metrics.accuracy_score(y_test, y_rc), 5))
print('precision =', round(metrics.precision_score(y_test, y_rc), 5))
print('recall =', round(metrics.recall_score(y_test, y_rc), 2))
print('f1 =', round(metrics.f1_score(y_test, y_rc), 2))

accuracy = 0.82418
precision = 0.75472
recall = 0.93
f1 = 0.83
